from typing import Dict, Type

from src.core.action.actions import (
    Action,
    AddContextAction,
    AddNoteAction,
    BashAction,
    BatchTodoAction,
    EditAction,
    FileMetadataAction,
    FinishAction,
    GlobAction,
    GrepAction,
    LSAction,
    LaunchSubagentAction,
    MultiEditAction,
    ReadAction,
    ReportAction,
    TaskCreateAction,
    UserInputAction,
    ViewAllNotesAction,
    WriteAction,
    WriteTempScriptAction,
)

ACTION_MAP: Dict[str, Type[Action]] = {
    "bash": BashAction,
    "finish": FinishAction,
    "user_input": UserInputAction,
    "todo": BatchTodoAction,
    "read_file": ReadAction,
    "write_file": WriteAction,
    "edit_file": EditAction,
    "multi_edit_file": MultiEditAction,
    "file_metadata": FileMetadataAction,
    "grep": GrepAction,
    "glob": GlobAction,
    "ls": LSAction,
    "add_note": AddNoteAction,
    "view_all_notes": ViewAllNotesAction,
    "task_create": TaskCreateAction,
    "add_context": AddContextAction,
    "launch_subagent": LaunchSubagentAction,
    "report": ReportAction,
    "write_temp_script": WriteTempScriptAction,
}
